echo commit

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -113,6 +113,10 @@ jobs:
       - name: Get ArgoCD admin password
         run: |
           ARGO_PWD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
+          if [ -z "$ARGO_PWD" ]; then
+            echo "Error: Failed to retrieve ArgoCD admin password."
+            exit 1
+          fi
           echo "::add-mask::$ARGO_PWD"
           echo "password=$ARGO_PWD" >> $GITHUB_OUTPUT
 
